# Generated by Django 3.1.3 on 2020-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201103_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile Phones', 'Mobile Phones'), ('Television', 'Television'), ('Air Conditioner', 'Air Conditioner')], max_length=200, null=True),
        ),
    ]
