# Generated by Django 3.1.3 on 2020-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201112_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='profile3.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bats', 'Bats'), ('Balls', 'Balls'), ('Pads', 'Pads'), ('Gloves', 'Gloves'), ('Safety Equipments', 'Safety Equipments'), ('Kits', 'Kits')], max_length=200, null=True),
        ),
    ]
