# Generated by Django 3.1.3 on 2020-11-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201120_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageLink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
