# Generated by Django 3.1.3 on 2020-11-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='notes',
        ),
    ]
