# Generated by Django 3.1.3 on 2020-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageLink',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
